services:
  backend:
    build:
      context: ./backend
    container_name: bulkmailer-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/app.log:/app/app.log

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: http://localhost:4000
    container_name: bulkmailer-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

